### ISSUE TITLE
wrf_load() should create a title

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/WRFmet#20]
The _RasterBrick_ S4 object has the following slots:

```
> slotNames(rasterBrick)
 [1] "file"     "data"     "legend"   "title"    "extent"   "rotated" 
 [7] "rotation" "ncols"    "nrows"    "crs"      "history"  "z"       
```

After running `wrf_load()`, the `@title` slot is currently empty. We should be able to read some attributes to create a title:

```
# global attributes:
> ncdf4::ncatt_get(nc, 0) %>% str() 
List of 146
 $ TITLE                         : chr " OUTPUT FROM WRF V4.1.3 MODEL"
 $ START_DATE                    : chr "2020-09-04_12:00:00"
 $ SIMULATION_START_DATE         : chr "2020-09-04_12:00:00"
 $ WEST-EAST_GRID_DIMENSION      : int 406
 $ SOUTH-NORTH_GRID_DIMENSION    : int 283
 $ BOTTOM-TOP_GRID_DIMENSION     : int 38
 ...

# specific variable attributes:
> ncdf4::ncatt_get(nc, nc$var[[12]]) %>% str()
List of 6
 $ FieldType  : int 104
 $ MemoryOrder: chr "XYZ"
 $ description: chr "z-wind component"
 $ units      : chr "m s-1"
 $ stagger    : chr "Z"
 $ coordinates: chr "XLONG XLAT XTIME"
```

It's probably worthwhile including the following utility function in this package: https://github.com/MazamaScience/MazamaSatelliteUtils/blob/master/R/utils-nc.R

I think we should probably rename this latter function to `nc_getAttributes()` as it is associated with _nc_ objects and accepts one as it's first argument.

This function can then be used in the `wrf_load()` function to add more information like `@title` to the _rasterBrick_ object.

**Comment by tabrasel** [comment]
My current idea for a generated raster title format is: `WRF Run @ 2020-08-27 12:00:00, Hour 7`

I hesitate to list the variable names/descriptions since there could be dozens. The AirFire default already includes about 20, and that would make the title string very, very long!

Also, it looks like the forecast hour (7 in this case) is missing from our WRF NetCDF file attributes. I think that information is pretty crucial to have in raster titles, so my solution is to just parse all of the date-time information directly from the file name. I'm not a huge fan of this method though, since a user might want to change their file names.
